apiVersion: v1
kind: ReplicaSet
metadata:
  name: my-replicaset # Name of the ReplicaSet       
  namespace: default # Namespace where the ReplicaSet is created
spec:
  replicas: 3 # Number of desired pods
  selector:
    matchLabels:
      app: my-app # Label selector to identify the pods managed by this ReplicaSet
  template:
    metadata:
      labels:
        app: my-app # Labels for the pod template
    spec:
      containers:
      - name: my-container # Name of the container
        image: nginx:latest # Container image to use
        ports:
        - containerPort: 80 # Port exposed by the container